### ISSUE TITLE
tlmgr: Local TeX Live (2022) is older than remote repository (2023)

### ISSUE THREAD

**Issue by rcalimlim** [yegor256/latexmk-action#11]
Hi there, I'm trying to use this GitHub Action in my project as such:

```yaml
name: build_check

on:
  pull_request:
    branches: [main]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sergeysova/jq-action@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: latexmk-action
        uses: yegor256/latexmk-action@0.7.1
        with:
          cmd: latexmk
          path: src/cv/tex/
          opts: -pdf
          packages: acmart tikz
```

when run in Actions, it produces this error:
`tlmgr: Local TeX Live (2022) is older than remote repository (2023)`

Among the results when searching that error is https://tex.stackexchange.com/questions/540429/tlmgr-in-ubuntu-20-04-local-tex-live-2019-is-older-than-remote-repository-2 which might be of help addressing this issue. Please let me know if you need more information to repro this issue.

Thanks
