### ISSUE TITLE
`tlmgr` error as wrong turn is taken in `entry.sh`

### ISSUE THREAD

**Issue by michaelcadilhac** [yegor256/latexmk-action#14]
`entry.sh` takes the `[[ "${INPUT_PACKAGES}" ]]` branch when no packages are asked for:

```
Run yegor256/latexmk-action@0.8.0
/usr/bin/docker run --name bedb44097556853054cbab937cb83d77f516c_3ec1e1 --label 5bedb4 --workdir /github/workspace --rm -e "INPUT_PATH" -e "INPUT_CMD" -e "INPUT_OPTS" -e "INPUT_PACKAGES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dotdepth/dotdepth":"/github/workspace" 5bedb4:4097556853054cbab937cb83d77f516c
+ set -e
+ cd /github/workspace
+ cd .
+ [[ -n   ]]
+ tlmgr --verify-repo=none update --self
tlmgr: package repository https://ctan.mirrors.hoobly.com/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr: saving backups to /usr/local/texlive/2023/tlpkg/backups
tlmgr: no self-updates for tlmgr available
+ tlmgr --verify-repo=none update
tlmgr update: specify --list, --all, --self, or a list of package names.
tlmgr: An error has occurred. See above messages. Exiting.
```

I suspect this is due to its default value as `' '`:

https://github.com/yegor256/latexmk-action/blob/3a7cee7bd188db124926d191117f73d370a010f5/action.yml#L47C5-L47C5

For reference, here's the workflow:
```
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: yegor256/latexmk-action@0.8.0
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: _build/main.pdf
```
